title = "Template 4"
# combining toml3 + cast_info stuff
# TODO: add movie_info join with preds on it on top of this and compare jl#s

[base_sql]
sql = '''SELECT n.gender, rt.role, cn.name, COUNT(*)
FROM title as t,
movie_companies as mc,
company_name as cn,
company_type as ct,
kind_type as kt,
cast_info as ci,
name as n,
role_type as rt,
movie_info as mi1,
info_type as it
WHERE t.id = mc.movie_id
AND t.id = ci.movie_id
AND t.id = mi1.movie_id
AND mi1.movie_id = ci.movie_id
AND ci.movie_id = mc.movie_id
AND cn.id = mc.company_id
AND ct.id = mc.company_type_id
AND kt.id = t.kind_id
AND ci.person_id = n.id
AND ci.role_id = rt.id
AND mi1.info_type_id = it.id
AND (Xmovie_kind)
AND (Xrole)
AND (Xprod_year_up)
AND (Xprod_year_low)
AND (Xit)
AND (Xmovie_info)
AND (Xcompany)
GROUP BY n.gender, rt.role, cn.name
ORDER BY COUNT(*) DESC
'''

# template 1
[[templates]]

  name = "1a"

  # all the unknown predicates in the base sql will be specified in groups
  [[templates.predicates]]
  type = "list"
  columns = ["t.production_year"]
  keys = ["Xprod_year_low", "Xprod_year_up"]
  dependencies = 0
  pred_type = "range"

  options = [[1875, 1945], [1945, 1990], [1990, 2015], [1875,
  2015]]
  sampling_method = "uniform"
  min_samples = 1
  max_samples = 1

  [[templates.predicates]]

  type = "sql"
  columns = ["rt.role"]
  keys = ["Xrole"]
  dependencies = 0
  pred_type = "IN"

  sql = '''
  SELECT rt.role, count(*)
  FROM role_type as rt
  GROUP BY rt.role
  '''

  sampling_method = "quantile"
  num_quantiles = 1
  min_samples = 3
  max_samples = 10

  [[templates.predicates]]
  type = "sql"
  columns = ["kt.kind"]
  keys = ["Xmovie_kind"]
  dependencies = 0

  sql = '''
  SELECT kt.kind
  FROM kind_type as kt
  '''

  pred_type = "ILIKE"
  thresholds = [1, 3, 5]
  min_count = 1
  min_chars = 1
  max_chars = 3

  [[templates.predicates]]
  type = "sql"
  columns = ["cn.name"]
  keys = ["Xcompany"]
  dependencies = 1
  pred_type = "ILIKE"
  thresholds = [500, 10000, 25000, 50000, 100000]
  min_chars = 2
  max_chars = 4

  sql = '''
  SELECT (cn.name)
  FROM company_name as cn, movie_companies as mc,
  title as t WHERE
  t.id = mc.movie_id
  AND cn.id = mc.company_id
  AND (Xprod_year_up)
  AND (Xprod_year_low)
  '''

  [[templates.predicates]]
  type = "sql"
  columns = ["it.id"]
  keys = ["Xit"]
  dependencies = 1
  pred_type = "IN"

  sql = '''
  SELECT it.id, count(*)
	FROM movie_info as mi, info_type as it
	WHERE mi.info_type_id = it.id
	GROUP BY it.id HAVING (COUNT(*) > 50000 AND
      COUNT(DISTINCT mi.info) < 500)
  ORDER BY COUNT(*) DESC
  '''

  sampling_method = "quantile"
  num_quantiles = 1
  min_samples = 1
  max_samples = 1

  [[templates.predicates]]
  type = "sql"
  columns = ["mi1.info"]
  keys = ["Xmovie_info"]
  dependencies = 1
  pred_type = "ILIKE"
  thresholds = [1000, 10000, 25000, 50000, 100000]
  min_count = 1
  min_chars = 1
  max_chars = 3

  sql = '''
  SELECT mi1.info
  FROM movie_info as mi1,
  info_type as it
  WHERE mi1.info_type_id = it.id
  AND (Xit)
  '''
